### PR TITLE
Updated nunjucks version to 2.0.0 as minimum, allowed Windows to run Mocha tests properly too

### PR DESCRIPTION
**Pull request by DaBs**
As title states. Furthermore fixes issues running tests on Windows machines, reference [here](https://github.com/carrot/roots-client-templates/issues/12).

### CODE REVIEW

**Comment by kristijanhusak** [comment]
Looks fine. Thanks!

**Comment by kristijanhusak** [comment]
@carlosl I'll need you to update npm.

**Comment by DaBs** [comment]
@kristijanhusak You'll need to push the package to the npm repo first. I just tried to run a fresh install from npm, but it's still the old version.

**Comment by kristijanhusak** [comment]
@DaBs I know, but i don't have access to the npm repo, only @carlosl does, so he needs to manage it.

**Pull request merged**
