### PR TITLE
update to pul#33

### PR DESCRIPTION
**Pull request by kamlekar**
Update to [pull#33](https://github.com/carlosl/gulp-nunjucks-render/pull/33) as [suggested](https://github.com/carlosl/gulp-nunjucks-render/pull/33#issuecomment-175669221)

### CODE REVIEW

**Comment by kristijanhusak** [comment]
@kamlekar 
It looks ok. Can you just add one test that will check this feature?

@carlosl We will need you later on this to update npm package.

**Comment by kamlekar** [comment]
Sorry, I don't know how to add a test.

**Comment by kristijanhusak** [comment]
Ok, i'll add it. Thanks for the PR.

**Comment by kamlekar** [comment]
Thanks :)

**Comment by woneob** [comment]
:+1:

**Comment by kristijanhusak** [comment]
@kamlekar I added the tests, and updated the version, but @carlosl needs to do the updating on npm.

@carlosl please add me as colaborator on npmjs so i can update npm after updates, here's my profile https://www.npmjs.com/~kristijanhusak

**Pull request merged**
