### PR TITLE
Update dependencies and add template inheritance and markdown handling

### LINKED ISSUE #52: Lodash issue
Please update lodash dependency to work around this issue:
https://github.com/lodash/lodash/commit/fe3d86bf13a3f136fc26265dce84d738a7aa490c

else we get:

```
[00:16:43] 'compileTemplatesStatic' errored after 145 ms
[00:16:43] TypeError: _.defaultsDeep is not a function
    at Object.module.exports (/Users/Zeno/Sites/Graffino/Projects/DotWhite/node_modules/gulp-nunjucks-render/index.js:18:15)
    at compileTemplatesStatic (/Users/Zeno/Sites/Graffino/Projects/DotWhite/gulp/bundle.js:128:19)
    at bound (domain.js:280:14)
    at runBound (domain.js:293:12)
    at asyncRunner (/Users/Zeno/Sites/Graffino/Projects/DotWhite/node_modules/async-done/index.js:36:18)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

### PR DESCRIPTION
**Pull request by mohitsinghs**
It fixes #52 #54 and everything I mentioned in #55.

### CODE REVIEW

**Comment by nikvm** [comment]
I would like to see this being merged. @carlosl are you still maintaining this plugin? Cheers.

**Comment by mohitsinghs** [comment]
Closing this as it seems like maintainer is no longer listening to us. I would instead consider using [webpack](http://webpack.js,org) or creating some utility for building static sites as they are still relevant.

**Comment by carlosl** [comment]
Sorry guys had been away, I was receiving help but will review some of the past pull requests today and try to push another version tonight.

**Comment by mohitsinghs** [comment]
@carlosl it's okay. This pull request is actually not complete. There are three points 

1. In the first commit, I updated dependencies and all tests passed successfully.
2. I modified your `data` option to handle both a path as a string and a data object. But there was a problem with my proposal which I solved later. I tried using `__dirname` to get data but I forgot that it works only if script is in project root. In the case of plugin it refers to the plugin directory and hence I solved it by using `path.resolve`. So this thing can be implement in your plugin.
3. What I exactly wanted is a feature like I explained [here](https://github.com/mohitsinghs/gulp-nunjucks-md/blob/master/readme.md) and in #55 and this, as far I know is a special use case and hence I created a [separate plugin](https://github.com/mohitsinghs/gulp-nunjucks-md) for people with similar use case.

So, this will be great if you can implement 1 and 2 but for 3 I have already created [a plugin](https://github.com/mohitsinghs/gulp-nunjucks-md) on the top of yours. I am currently using both your and mine plugin for two different projects due to different use cases (To handle markdown and front-matter).
I am using that plugin to create a production website with a lot of typographical content (and hence markdown). Please correct me and share your thoughts on it. Thank you.

**Pull request closed without merging**
