### PR TITLE
Bump nunjucks version to 2.0 or higher

### PR DESCRIPTION
**Pull request by kevinmpowell**
I've tested my fork with Travis CI and all 7 tests pass. I'm also running this version in one of my projects locally without any issues.

### CODE REVIEW

**Comment by kamlekar** [comment]
@carlosl Please act. Thanks.

**Comment by kamlekar** [comment]
@carlosl Please act. Thanks. @kristijanhusak can you update as necessary?

**Comment by kristijanhusak** [comment]
@kevinmpowell tests are failing here. Do you know why?

**Comment by kamlekar** [comment]
@kristijanhusak As I can see in the commits, this [change](https://github.com/kevinmpowell/gulp-nunjucks-render/commit/58853c1b1719a0a4f5b55979b9de3cef425417fd) is failing the build.

**Comment by kristijanhusak** [comment]
@kamlekar Yes, but proper version of nunjucks is installed before tests are run, see this line https://travis-ci.org/carlosl/gulp-nunjucks-render/builds/91411767#L128 .

**Comment by kristijanhusak** [comment]
Closing this since version was bumped here https://github.com/carlosl/gulp-nunjucks-render/pull/31

**Pull request closed without merging**
